// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyxuwjdokklcnkmmkkeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eHV3amRva2tsY25rbW1ra2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzA5MTQsImV4cCI6MjA3ODIwNjkxNH0.ZVdgjhdhghRiq_F82z8XB3lOfK0hXD8hnoXHFIJdzD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});